### ISSUE TITLE
Crash with android 6

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [manojdcoder/titanium-mupdf#22]
The module working fine on android version but on android 6 go crash 
TiApplication: (main) [2827,9010] Sending event: exception on thread: main msg:java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View android.widget.Adapter.getView(int, android.view.View, android.view.ViewGroup)' on a null object reference; Titanium 5.2.0,2016/02/20 08:05,384775e
[ERROR] TiApplication: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View android.widget.Adapter.getView(int, android.view.View, android.view.ViewGroup)' on a null object reference
[ERROR] TiApplication: 	at com.artifex.mupdflib.ReaderView.getOrCreateChild(ReaderView.java:843)
[ERROR] TiApplication: 	at com.artifex.mupdflib.ReaderView.onLayout(ReaderView.java:717)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
[ERROR] TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
[ERROR] TiApplication: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
[ERROR] TiApplication: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
[ERROR] TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
[ERROR] TiApplication: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
[ERROR] TiApplication: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
[ERROR] TiApplication: 	at android.view.View.layout(View.java:16630)
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
[ERROR] TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
[ERROR] TiApplication: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
[ERROR] TiApplication:
[ERROR] TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:5437)
[ERROR] TiApplication: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
[ERROR] TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
[ERROR] TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
[ERROR] TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
[ERROR] TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
[ERROR] TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
[ERROR] TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
[ERROR] TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
[ERROR] TiApplication: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.j

**Comment by m1ga** [comment]
this helped me: https://github.com/manojdcoder/titanium-mupdf/issues/10#issuecomment-115431674
it wasn't working with a file in resource directory but from an external storage. Keep in mind that you'll need the new storage permission on android 6

**Comment by manojdcoder** [comment]
Closing this issue considering Michael's solution fixes it.
