### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by dholler** [manojdcoder/titanium-mupdf#24]
Hi,
first of all thanks for your effort on this module, but it does not work.

When running your example code the app crashes with following error:

> [INFO]  >>EXISTS>>>true
> [DEBUG] PDFReaderProxy: (main) [369,369] PDF exists, trying to load
> [DEBUG] PDFReaderProxy: (main) [0,369] Trying to open /storage/emulated/0/de.onestytech.apps.demos/sample.pdf
> [WARN]  W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.onestytech.apps.demos-2/base.apk"],nativeLibraryDirectories=[/data/app/de.onestytech.apps.demos-2/lib/arm, /data/app/de.onestytech.apps.demos-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libmupdf.so"
> [WARN]  W/System.err: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
> [WARN]  W/System.err: 	at java.lang.System.loadLibrary(System.java:1076)
> [WARN]  W/System.err: 	at com.artifex.mupdflib.MuPDFCore.<clinit>(MuPDFCore.java:17)
> [WARN]  W/System.err: 	at com.mykingdom.mupdf.ViewProxy$PDFReaderView.openFile(ViewProxy.java:146)
> [WARN]  W/System.err: 	at com.mykingdom.mupdf.ViewProxy$PDFReaderView.processProperties(ViewProxy.java:117)
> [WARN]  W/System.err: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1173)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:510)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
> [WARN]  W/System.err: 	at com.mykingdom.mupdf.ViewProxy.getPDFReaderView(ViewProxy.java:243)
> [WARN]  W/System.err: 	at com.mykingdom.mupdf.ViewProxy.setScrollingDirection(ViewProxy.java:309)
> [WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
> [WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:196)
> [WARN]  W/System.err: 	at org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:241)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.loadActivityScript(TiLaunchActivity.java:128)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.windowCreated(TiLaunchActivity.java:183)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiRootActivity.windowCreated(TiRootActivity.java:172)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:682)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.onCreate(TiLaunchActivity.java:169)
> [WARN]  W/System.err: 	at org.appcelerator.titanium.TiRootActivity.onCreate(TiRootActivity.java:161)
> [WARN]  W/System.err: 	at android.app.Activity.performCreate(Activity.java:6904)
> [WARN]  W/System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
> [WARN]  W/System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3252)
> [WARN]  W/System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3401)
> [WARN]  W/System.err: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
> [WARN]  W/System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
> [WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> [WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:148)
> [WARN]  W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7303)
> [WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> [WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
> [WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Anything I can do to get around that error?

Using SDK 6.0.3.GA on an Samsung Galaxy Tab A Running Android 6.0.1.

Thanks in advance, Dom.

**Comment by jerry42** [comment]
Hi !
Same problem here. Are you still working on this module or do I need to start searching for another solution ?
Thanks for the work anyway !

**Comment by manojdcoder** [comment]
I personally switched to NativeScript now, so I'm not working on this module any more. You can hire me (or someone else) if you need a fix.

**Comment by jerry42** [comment]
Ok thanks I will take a look around.

**Comment by focussing** [comment]
Hello @jerry42 , have you found another module?
Looking forward to hearing from you.
